### ISSUE TITLE
Associativity not taken into account for 'DataStructures-in-JavaScript/Stacks/InfixToPrefix.js'

### ISSUE THREAD

**Issue by grumpycornball** [aditya278/DataStructures-in-JavaScript#2]
Operators like '+' and '-' has left to right associativity,so nothing to worry there. But in case of '^' associativity goes from right to left which is not considered in your java script program. 

**For example:** 
2^2^3 is calculated as 2^(8) = 256.
But as per expression from your output, value will get evaluated as 2^2^3=(4)^3=64, which is wrong.

**i/p:** a^b^c
**o/p from your code:** ab^c^
**expected o/p:** abc^^

This issue is opened with an assumption that below mentioned issue is valid,if not then please discard/close both the issues.
https://github.com/aditya278/DataStructures-in-JavaScript/issues/1

**Comment by aditya278** [comment]
Good catch. The equality operator in the precedence checking logic was the reason for this issue.
